# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-28 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_cache', '0003_drop_timeline'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestCache',
        ),
    ]
